// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnalysisTabsController from "./analysis_tabs_controller"
application.register("analysis-tabs", AnalysisTabsController)

import BudgetCalculatorController from "./budget_calculator_controller"
application.register("budget-calculator", BudgetCalculatorController)

import CriteriaSearchController from "./criteria_search_controller"
application.register("criteria-search", CriteriaSearchController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FadeInController from "./fade_in_controller"
application.register("fade-in", FadeInController)

import FadeRemoveController from "./fade_remove_controller"
application.register("fade-remove", FadeRemoveController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import InspectionItemController from "./inspection_item_controller"
application.register("inspection-item", InspectionItemController)

import LoanSliderController from "./loan_slider_controller"
application.register("loan-slider", LoanSliderController)

import NumberFormatController from "./number_format_controller"
application.register("number-format", NumberFormatController)

import ProfitCalculatorController from "./profit_calculator_controller"
application.register("profit-calculator", ProfitCalculatorController)

import PropertyFilterController from "./property_filter_controller"
application.register("property-filter", PropertyFilterController)

import RegionSelectController from "./region_select_controller"
application.register("region-select", RegionSelectController)

import ReserveFundController from "./reserve_fund_controller"
application.register("reserve-fund", ReserveFundController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SourceDocReviewController from "./source_doc_review_controller"
application.register("source-doc-review", SourceDocReviewController)

import SourceDocTrackerController from "./source_doc_tracker_controller"
application.register("source-doc-tracker", SourceDocTrackerController)

import StickyHeaderController from "./sticky_header_controller"
application.register("sticky-header", StickyHeaderController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import UnifiedFormController from "./unified_form_controller"
application.register("unified-form", UnifiedFormController)
