class RenameInspectionTabEnumValues < ActiveRecord::Migration[8.1]
  # Old enum: sale_document(0), registry(1), building_ledger(2), online(3), field_visit(4), etc(5)
  # New enum: rights_analysis(0), property_analysis(1), profit_analysis(2), field_check(3), bidding(4)
  #
  # Since the integer values are reused with new meanings, we must:
  # 1. Clear existing inspection_results (they reference old tab assignments)
  # 2. Clear existing inspection_items (will be re-seeded)
  # This is safe because seed data is the source of truth for inspection_items,
  # and inspection_results are regenerated by PropertyInspectionService.

  def up
    # Remove dependent results first (foreign key constraint)
    execute "DELETE FROM inspection_results"
    execute "DELETE FROM inspection_items"
  end

  def down
    # Reverse migration also clears data; re-seed needed
    execute "DELETE FROM inspection_results"
    execute "DELETE FROM inspection_items"
  end
end
